/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

useGLTF.preload('/ficha.glb');
export function FichaRoja({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"red"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
export function FichaAmarilla({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"yellow"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
export function FichaVerde({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"green"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
export function FichaAzul({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"blue"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
export function FichaMorada({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"purple"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
export function FichaNaranja({...props}){
  const group = useRef();
  const { nodes, materials } = useGLTF('/ficha.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Fichas.geometry}
        material={nodes.Fichas.material}
        position={[props.x, props.y, props.z]}
        material-color={"orange"}
        onClick={()=>console.log(props)}
      />
    </group>
  );
}
